spring.application.name=cert-book-review

server.servlet.encoding.force=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb

spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

# API 키는 application-local.properties에 작성 (git 제외)
spring.config.import=optional:classpath:application-local.properties

naver.client-id=
naver.client-secret=

qnet.service-key=
